c_cont_score_thresh = 0.95 # better than this, we don't bother trying to find more clauses
c_cont_score_min = 0.1
c_cont_min_tests = 10
c_num_turns_per_play = 15
c_num_plays = 530
c_expands_min_tries = 30
c_expands_score_thresh = 0.95
c_expands_score_min_thresh = 0.1
c_score_loser_penalty = 1
c_score_winner_bonus = 5
